class FashionItem {
  final String name;
  final double price;
  final String description;
  final List<String> sizes;
  final String image;
  final String category;

  FashionItem({
    required this.name,
    required this.price,
    required this.description,
    required this.sizes,
    required this.image,
    required this.category,
  });
}
final List<FashionItem> fashionItems = [
  FashionItem(
    name: "Classic T-Shirt",
    price: 19.99,
    description: "Comfortable cotton t-shirt for daily wear.",
    sizes: ["S", "M", "L", "XL"],
    image: "asset/image/T_Shirt.png",
    category: "Male",
  ),
  FashionItem(
    name: "Summer Dress",
    price: 29.99,
    description: "Floral lightweight dress for summer.",
    sizes: ["S", "M", "L"],
   image: "asset/image/Summer_Dress.png",
    category: "Female",
  ),
  FashionItem(
    name: "Kids Hoodie",
    price: 24.99,
    description: "Warm hoodie perfect for children.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Kids_Hoodie.png",
    category: "Kid",
  ),
  FashionItem(
    name: "Sneakers",
    price: 49.99,
    description: "Trendy sneakers for casual outings.",
    sizes: ["M", "L", "XL"],
    image: "asset/image/Sneakers.webp",
    category: "Male",
  ),
  FashionItem(
    name: "Women's Heels",
    price: 59.99,
    description: "Elegant heels for special occasions.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Heels.webp",
    category: "Female",
  ),
  FashionItem(
    name: "Sunglasses",
    price: 15.99,
    description: "Stylish shades for any look.",
    sizes: [],
    image: "asset/image/Sunglasses.png",
    category: "Life style",
  ),
  FashionItem(
    name: "Graphic Tee",
    price: 21.99,
    description: "Printed t-shirt with unique design.",
    sizes: ["S", "M", "L", "XL"],
    image: "asset/image/Graphic_Tee.png",
    category: "Male",
  ),
  FashionItem(
    name: "Casual Blouse",
    price: 27.99,
    description: "Loose blouse for everyday wear.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Casual Blouse.png",
    category: "Female",
  ),
  FashionItem(
    name: "Jacket",
    price: 35.99,
    description: "Durable jacket for young boys.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Jacket.webp",
    category: "Kid",
  ),
  FashionItem(
    name: "Backpack",
    price: 39.99,
    description: "Spacious and trendy backpack.",
    sizes: [],
    image: "asset/image/Backpack.png",
    category: "Life style",
  ),
  FashionItem(
    name: "Slim Fit Jeans",
    price: 44.99,
    description: "Modern slim-fit blue jeans.",
    sizes: ["M", "L", "XL"],
    image: "assets/image/Jeans.png",
    category: "Male",
  ),
  FashionItem(
    name: "Evening Gown",
    price: 89.99,
    description: "Stunning gown for evening events.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Evening_Gown.webp",
    category: "Female",
  ),
  FashionItem(
    name: "Skirt",
    price: 22.99,
    description: "Cute and comfy skirt for girls.",
    sizes: ["S", "M", "L"],
    image: "asset/image/Skirt.webp",
    category: "Kid",
  ),
  FashionItem(
    name: "Leather Wallet",
    price: 19.99,
    description: "Compact and stylish wallet.",
    sizes: [],
    image: "asset/image/Wallet.png",
    category: "Life style",
  ),
  FashionItem(
    name: "Men's Jacket",
    price: 69.99,
    description: "Waterproof and windproof jacket.",
    sizes: ["M", "L", "XL"],
    image: "asset/image/Jacket.webp",
    category: "Male",
  ),
  FashionItem(
    name: "Sports Bra",
    price: 34.99,
    description: "Supportive bra for workout sessions.",
    sizes: ["S", "M", "L"],
   image: "asset/image/Sports_Bra.webp",
    category: "Female",
  ),
  FashionItem(
    name: "Kid's Cap",
    price: 9.99,
    description: "Cool cap for sunny days.",
    sizes: [],
    image: "asset/image/Cap.png",
    category: "Kid",
  ),
  FashionItem(
    name: "Digital Watch",
    price: 49.99,
    description: "Modern digital watch for any outfit.",
    sizes: [],
    image: "asset/image/kid_dress.webp",
    category: "Life style",
  ),
  FashionItem(
    name: "Cotton Shorts",
    price: 25.99,
    description: "Relaxed shorts for warm weather.",
    sizes: ["S", "M", "L", "XL"],
    image: "asset/image/kid_dress.webp",
    category: "Male",
  ),
  FashionItem(
    name: "Floral Top",
    price: 28.99,
    description: "Bright floral top for spring vibes.",
    sizes: ["S", "M", "L"],
    image: "asset/images/kid_dress.webp",
    category: "Female",
  ),
];
